# Generated by Django 5.0.2 on 2024-03-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Railway',
            fields=[
                ('Train_no', models.IntegerField(primary_key=True, serialize=False)),
                ('Train_name', models.CharField(max_length=50)),
                ('Start_station_code', models.CharField(max_length=20)),
                ('End_station_code', models.CharField(max_length=20)),
                ('Start_date', models.DateTimeField()),
                ('End_date', models.DateTimeField()),
            ],
        ),
    ]
